---
- name: Check Free Filesystem Space
  hosts: 10.1.1.2
  tasks:
    
  
    - name: Copy config file to destination
      ansible.builtin.copy:
        src: repo1 # Path relative to the root of your Git repo
        dest: /tmp # Destination path on the remote server
        owner: root
        group: root
        mode: '0644'

     - name: Run date command
       ansible.builtin.command: date
       register: command_output

    - name: Display command output
      ansible.builtin.debug:
        var: command_output.stdout
    
    
