---

- hosts: osboxes4
  gather_facts: no
  tasks:
    
    - name: Uninstall apache2 package
      apt:
        name: apache2
        state: absent

    - name: Install apache2 package
      apt:
        name: apache2
        state: present
