---
- name: Check Free Filesystem Space
  hosts: 10.1.1.2
  tasks:
        
    - name: Run df command
      ansible.builtin.command: df -h
      register: command_output

    - name: Display command output
      ansible.builtin.debug:
        msg: " {{ command_output.stdout_lines }}"
