name: CopyRepo

on:
  workflow_dispatch:
    

jobs:
  Copy-Repo-10-1-1-2:

    runs-on: ubuntu2
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: dxmohan/project4.git # Replace with your source repo
          ref: releases/101010 # The branch to checkout
          token: ${{ secrets.PAT_TOKEN1 }} # Use the PAT for necessary permissions

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Make changes (example)
        # Add your commands here to modify files as needed
        run: |
          echo "Sync completed at $(date)" > sync_status.txt
          git add sync_status.txt
          git commit -m "Automated sync changes"

      - name: Push to Destination Repository
        run: |
          # Add the destination repository as a new remote
          git remote add destination https://github.com/dxmohan/project1.git
          
          # Push the changes to the destination repository using the PAT for authentication
          # Use a variable to prevent the PAT from being exposed in logs
          REPO_URL="https://${{ secrets.PAT_TOKEN1 }}@://github.com/dxmohan/project1.git"
          git push $REPO_URL releases/101010:releases/C101013 # Push local main to remote main, replace branch names as needed
   
       
